### ISSUE TITLE
Spec Issues

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/flatiron-store-project#1] opened 2016-02-17 01:53 UTC
Spec does not properly initialize with a user. DB cleaner runs before specs, and seed file does not seed any user data, causing:

@user = User.first

to return nil.

**Comment by AnnJohn** [comment] 2016-02-23 17:17
thanks @jakebrady5. We will be fixing Rails issues within the next few weeks so will get to this soon.

**Comment by c1505** [comment] 2016-03-17 02:49
still broken

**Comment by aturkewi** [comment] 2016-03-30 13:52
As @jakebrady5 pointed out, there is no User data in the seed file, so when the test runs, and gets `@user = User.first` for testing, `@user = nil`. Up until this point in the curriculum, students are not generally expected to be adding to the seed data so I would say it is far from their first instinct when they are running tests and getting "Undefined method `#current_cart` on nil class" (or something along those lines. Two possible solutions:
1. Make it clear to students in the README that they must add at least one user to the seed file. I kind of like this option because this is the final rails project and I think it make sense that students do at least a little work in the seed file.
2. Add a user to the seed file so that when students run the test, there is a User.first available. 

Shout out to @PeterBell

**Comment by PeterBell** [comment] 2016-03-30 14:12
Thanks for the heads up @aturkewi I'd love input from @jmburges on this one stylistically. Adding the seed data is a simple fix, but should we use this as a chance for students to learn how to add seed data and maybe just give them a hint that they need to make sure they have all the seed data they need. Joe? Would love if we could prioritize this as it's hurting a lot of students.

**Comment by jmburges** [comment] 2016-03-30 14:30
Students have seen the concept of seeding many times so far in the curriculum. While it is correct that they have never actually written a seed file they have seen it in probably 10+ times in previous labs. I 100% believe we should mention to the student that they will need to add items to the seed file and link them an outside resource or give them some google terms to google to find out how to do it. I bet most students will find the idea of writing to a `seeds.rb` file fairly familiar and reasonable.

Question is, should we explain to them _what_ needs to be added to the seeds file. I think the answer is no. This is the final Rails project, they should be pros at reading error messages. Giving them a heads up that they'll hit issues running the tests and those issues should be solvable with a seeds file is enough of a push in the right direction.

**Comment by PeterBell** [comment] 2016-03-30 14:33
Awesome - thanks @jmburges - that's all the input I need. Let me take a run at this.

**Comment by PeterBell** [comment] 2016-03-30 15:22
OK @jmburges would the PR above work? https://github.com/learn-co-curriculum/flatiron-store-project/pull/7

**Comment by c1505** [comment] 2016-03-30 15:55
As a student going through the labs, my expectation has always been that I shouldn't be modifying the test in order to get it to pass.  If the tests are going to be broken out of the gate by design, I think it should be really clear that they are and something needs to be changed in order for them to work correctly.  Also, why is the gem factory-girl there when it isn't being used?

**Comment by PeterBell** [comment] 2016-04-06 14:42
Hey @c1505 thanks for the feedback - checking with the team now whether it makes sense to merge #7  as a fix. Re: factory girl, would you mind opening a separate issue if a separate question? Sorry - just trying to keep each issue on topic and focused. Thanks!

**Comment by PeterBell** [comment] 2016-04-06 14:43
Hey @pletcher cc @AnnJohn what do you think of #7 as a fix for this? Would like to get this merged if it's OK. Also cc @jmburges

**Closed as completed** 2016-04-06 15:50 UTC
